version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 098poiA#    # Mật khẩu root
      MYSQL_DATABASE: spring_security     # Tên schema (database)
      MYSQL_USER: user                # Tên người dùng
      MYSQL_PASSWORD: password        # Mật khẩu của người dùng
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring_security_network

volumes:
  mysql_data:

networks:
  spring_security_network:
    driver: bridge